<?php
/**
 * @file
 * Code for the Blog feature.
 */

include_once('ceardach_blog.features.inc');

/**
 * Implementation of hook_block_view_BLOCK_DELTA_alter().
 */
function ceardach_blog_block_view_tagadelic_1_alter(&$data, $block) {
  // Changing the title of the tagdelic block
  $data['subject'] = 'topics';
}

/**
 * Implementation of hook_node_view().
 */
function ceardach_blog_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'teaser') {
    // Add a 'continue...' link to the end of the teaser, before the paragraph
    // ends
    $content = $node->content['body'][0]['#markup'];
    if (substr($content, -4) == '</p>') {
      $link = l('continue ...', 'node/'. $node->nid, array('attributes' => array('class' => array('read-more'))));
      $content = substr_replace($content, '&nbsp;&nbsp;'. $link .'</p>', strlen($content)-4, strlen($content));
      $node->content['body'][0]['#markup'] = $content;
    }
  }
}
